language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - pip install ipython
  - pip install --install-option='--no-cython-compile' -r dev_requirements.txt
  - python setup.py develop
script:
  - python -m unittest discover -v tests
notifications:
  email:
      - robert.kern+travis-ci@gmail.com
