language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
install:
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - python -m unittest discover -v tests
notifications:
  email:
      - robert.kern+travis-ci@gmail.com
